/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import {  useLoader } from '@react-three/fiber'
import { TextureLoader } from 'three/src/loaders/TextureLoader'

export default function ModelPackingBag(props) {
  const name = (number) => `Textures${number}.jpg`;
  const { childData } = props;

  function Scene() {
    const colorMap = useLoader(TextureLoader, name(childData));
    return (
      <>
        <mesh
        castShadow
        receiveShadow
        geometry={nodes.body.geometry}
        material={nodes.body.material}
        position={[0, 17.16, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.97, 0.88, 1]}
        >
          <meshStandardMaterial map={colorMap} />
        </mesh>
        <mesh
        castShadow
        receiveShadow
        geometry={nodes.rope1.geometry}
        material={nodes.rope1.material}
        position={[4.85, 37.32, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1, 1.05, 1.05]}
        >
        </mesh>
        <mesh
       castShadow
       receiveShadow
       geometry={nodes.rope2.geometry}
       material={nodes.rope2.material}
       position={[-4.81, 37.24, 0]}
       rotation={[0, Math.PI / 2, 0]}
       scale={[1, 1.05, 1.05]}
        >
        </mesh>
      </>
    );
  }
    const group = useRef()
    const { nodes } = useGLTF('/gltf/handbag.gltf')
  
    // const colorMap = useLoader(TextureLoader, 'PavingStones092_1K_Color.jpg')
    return (
      <group ref={group} dispose={null}>
        <Scene/>
      </group>
    )
  }

useGLTF.preload("/gltf/handbag.gltf");
