/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import {  useLoader } from '@react-three/fiber'
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { Material } from "three";

export default function ModelPackingBag(props) {
  // const name = (number) => `Textures${number}.jpg`;
  const { childData } = props;

  function Scene() {
    const colorMap = useLoader(TextureLoader, childData);
    return (
      <>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.立方体.geometry}
          >
          <meshStandardMaterial map={colorMap}/>
        </mesh>
      </>
    );
  }
    const group = useRef()
    const { nodes } = useGLTF('/gltf/packingBag.glb')
  
    // const colorMap = useLoader(TextureLoader, 'PavingStones092_1K_Color.jpg')
    return (
      <group ref={group} dispose={null}>
        <Scene/>
      </group>
    )
  }

useGLTF.preload("/gltf/packingBag.glb");
